import { NextRequest, NextResponse } from 'next/server';
import { getSessionUser } from '@/lib/auth';
import { db } from '@/lib/db';
import { v4 as uuidv4 } from 'uuid';

export async function GET() {
  const user = await getSessionUser();
  if (!user) return NextResponse.json({ error: 'Not authenticated' }, { status: 401 });

  const tags = db.getTagsForUser(user.id);
  return NextResponse.json({ tags });
}

export async function POST(req: NextRequest) {
  const user = await getSessionUser();
  if (!user) return NextResponse.json({ error: 'Not authenticated' }, { status: 401 });

  const { name, color } = await req.json();
  if (!name?.trim()) return NextResponse.json({ error: 'Tag name required' }, { status: 400 });

  const tagId = db.upsertTag({
    id: uuidv4(),
    name: name.trim().toLowerCase(),
    userId: user.id,
    autoGenerated: false,
    color: color || '#6366f1',
  });

  return NextResponse.json({ success: true, tagId });
}

export async function DELETE(req: NextRequest) {
  const user = await getSessionUser();
  if (!user) return NextResponse.json({ error: 'Not authenticated' }, { status: 401 });

  const { id } = await req.json();
  if (!id) return NextResponse.json({ error: 'Tag id required' }, { status: 400 });

  db.deleteTag(id);
  return NextResponse.json({ success: true });
}
