import { NextRequest, NextResponse } from 'next/server';
import { getSessionUser } from '@/lib/auth';
import { db } from '@/lib/db';
import { v4 as uuidv4 } from 'uuid';

export async function GET(req: NextRequest, { params }: { params: { id: string } }) {
  const user = await getSessionUser();
  if (!user) return NextResponse.json({ error: 'Not authenticated' }, { status: 401 });

  const file = db.getFile(params.id);
  if (!file || file.user_id !== user.id) {
    return NextResponse.json({ error: 'File not found' }, { status: 404 });
  }

  const tags = db.getTagsForFile(params.id);
  return NextResponse.json({ tags });
}

export async function POST(req: NextRequest, { params }: { params: { id: string } }) {
  const user = await getSessionUser();
  if (!user) return NextResponse.json({ error: 'Not authenticated' }, { status: 401 });

  const file = db.getFile(params.id);
  if (!file || file.user_id !== user.id) {
    return NextResponse.json({ error: 'File not found' }, { status: 404 });
  }

  const { name, tagId } = await req.json();

  if (tagId) {
    db.linkFileTag(params.id, tagId);
  } else if (name?.trim()) {
    const newTagId = db.upsertTag({
      id: uuidv4(),
      name: name.trim().toLowerCase(),
      userId: user.id,
      autoGenerated: false,
    });
    db.linkFileTag(params.id, newTagId);
  } else {
    return NextResponse.json({ error: 'Tag name or tagId required' }, { status: 400 });
  }

  return NextResponse.json({ success: true, tags: db.getTagsForFile(params.id) });
}
